services:
  frontend:
    image: jlh-autopam-frontend:latest
    build: .
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jlh-autopam-frontend.rule=Host(`${FRONTEND_HOSTNAME}`)
      - traefik.http.routers.jlh-autopam-frontend.entrypoints=websecure
      - traefik.http.routers.jlh-autopam-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.jlh-autopam-frontend.loadbalancer.server.port=3000
    networks:
      - jlh

networks:
  jlh:
    external: true
