services:
  frontend:
    image: steve57/jlh-autopam-frontend:latest
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.jlh-autopam-frontend.rule=Host(`jlh-autopam.fr`) || Host(`www.jlh-autopam.fr`)
      - traefik.http.routers.jlh-autopam-frontend.entrypoints=websecure
      - traefik.http.routers.jlh-autopam-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.jlh-autopam-frontend.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - jlh

networks:
  jlh:
    external: true
