upstream jlh_backend {
    server backend:8080;
}

upstream jlh_frontend {
    server frontend:4000;
}

server {
    listen 80;
    server_name api.example.com;

    # Service Nginx pour les uploads (images, icônes, etc.)
    location /uploads/ {
        alias /var/www/promo/;
        autoindex off;
        expires 1d;
        add_header Cache-Control "public";
    }

    # Service Nginx pour les images de promotion
    location /promotions/images/ {
        alias /var/www/promo/images/;
        autoindex off;
        expires 1d;
        add_header Cache-Control "public";
    }

    # Service Nginx pour les icônes (cache long)
    location /icons/ {
        alias /var/www/promo/icons/;
        autoindex off;
        expires 30d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://jlh_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name app.example.com;

    location / {
        proxy_pass http://jlh_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
