name: CI/CD Frontend

on:
  push:
    branches:
      - main
      - dev

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev-${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/jlh-autopam-frontend:${{ env.TAG }}
